### ISSUE TITLE
esphomeyaml  dashboard shwoing terminated process

### ISSUE THREAD

**Issue by eramanaraju** [esphome/esphome#480]
[32mINFO Running command 'esphomeyaml --dashboard config/err.yaml run --upload-port COM3'[0m
[31mERROR Uncaught exception GET /run (::1)
HTTPServerRequest(protocol='http', host='localhost:6052', method='GET', uri='/run', version='HTTP/1.1', remote_ip='::1')[0m
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\tornado\websocket.py", line 546, in _run_callback
    result = callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\esphomeyaml\dashboard\dashboard.py", line 73, in on_message
    stderr=subprocess.STDOUT)
  File "c:\python27\lib\site-packages\tornado\process.py", line 228, in __init__
    out_r, out_w = _pipe_cloexec()
  File "c:\python27\lib\site-packages\tornado\process.py", line 91, in _pipe_cloexec
    set_close_exec(r)
  File "c:\python27\lib\site-packages\tornado\platform\windows.py", line 20, in set_close_exec
    raise ctypes.WinError()
WindowsError: [Error 6] The handle is invalid.[0m
[32mINFO 101 GET /run (::1) 2.00ms[0m
[32mINFO Running command 'esphomeyaml --dashboard config/err.yaml run --upload-port COM3'[0m
[31mERROR Uncaught exception GET /run (::1)
HTTPServerRequest(protocol='http', host='localhost:6052', method='GET', uri='/run', version='HTTP/1.1', remote_ip='::1')[0m
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\tornado\websocket.py", line 546, in _run_callback
    result = callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\esphomeyaml\dashboard\dashboard.py", line 73, in on_message
    stderr=subprocess.STDOUT)
  File "c:\python27\lib\site-packages\tornado\process.py", line 232, in __init__
    self.stdout = PipeIOStream(out_r)
  File "c:\python27\lib\site-packages\tornado\iostream.py", line 1723, in __init__
    _set_nonblocking(fd)
TypeError: 'NoneType' object is not callable[0m
[32mINFO 200 GET / (::1) 8.00ms[0m
[32mINFO 304 GET /edit?configuration=livingroom.yaml (::1) 2.00ms[0m
[32mINFO 101 GET /run (::1) 1.00ms[0m
[32mINFO Running command 'esphomeyaml --dashboard config/livingroom.yaml run --upload-port OTA'[0m
[31mERROR Uncaught exception GET /run (::1)
HTTPServerRequest(protocol='http', host='localhost:6052', method='GET', uri='/run', version='HTTP/1.1', remote_ip='::1')[0m
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\tornado\websocket.py", line 546, in _run_callback
    result = callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\esphomeyaml\dashboard\dashboard.py", line 73, in on_message
    stderr=subprocess.STDOUT)
  File "c:\python27\lib\site-packages\tornado\process.py", line 232, in __init__
    self.stdout = PipeIOStream(out_r)
  File "c:\python27\lib\site-packages\tornado\iostream.py", line 1723, in __init__
    _set_nonblocking(fd)
TypeError: 'NoneType' object is not callable[0m

**Comment by OttoWinter** [comment]
https://github.com/esphome/esphome/issues/430

tornado (and thus the websocket) is incompatible with windows
